// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/SSERPC/Registration.ts";
import * as $1 from "./routes/SSERPC/Requests.ts";
import * as $2 from "./routes/SSERPC/db.ts";
import * as $3 from "./routes/SSERPC/_middleware.ts";
import * as $4 from "./routes/index.tsx";

const manifest = {
  routes: {
    "./routes/SSERPC/Registration.ts": $0,
    "./routes/SSERPC/Requests.ts": $1,
    "./routes/SSERPC/db.ts": $2,
    "./routes/SSERPC/_middleware.ts": $3,
    "./routes/index.tsx": $4,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
