// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/dispatch.ts";
import * as $1 from "./routes/api/post.ts";
import * as $2 from "./routes/index.tsx";

const manifest = {
  routes: {
    "./routes/api/dispatch.ts": $0,
    "./routes/api/post.ts": $1,
    "./routes/index.tsx": $2,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
